apiVersion: v1
kind: Service
metadata:
  namespace: ns-cafeapp
  name: cafeapp-service
spec:
  selector:
    app: cafeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30017
  type: NodePort
